INC_COMP=../../../../../components/include/
INC_KERN=../../../../../kernel/include/shared/

all:
	gcc -I $(INC_COMP) -I $(INC_KERN) -o hello hello.c

debug:
	gcc -g -I $(INC_COMP) -I $(INC_KERN) -o hello hello.c